export const PRODUCT_OPERATION_STARTED = 'PRODUCT_OPERATION_STARTED';
export const PRODUCT_OPERATION_FAILED = 'PRODUCT_OPERATION_FAILED';

export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const PRODUCT_SAVED = 'PRODUCT_SAVED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
