export const ITEM_OPERATION_STARTED = 'ITEM_OPERATION_STARTED';
export const ITEM_OPERATION_FAILED = 'ITEM_OPERATION_FAILED';
export const ITEM_UPDATE_FAILED = 'ITEM_OPERATION_FAILED';

export const ITEMS_FETCHED = 'ITEMS_FETCHED';
export const ITEM_SAVED = 'ITEM_SAVED';
export const ITEM_DELETED = 'ITEM_DELETED';
